services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: ${DB_CONTAINER}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    container_name: ${WP_CONTAINER}
    depends_on:
      - db
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','${WP_URL}');
        define('WP_SITEURL','${WP_URL}');
    volumes:
      - ./wp-content:/var/www/html/wp-content

  wp-tests:
    image: wordpress:php8.2-apache
    depends_on:
      - db
    working_dir: /workspace
    environment:
      WP_CORE_DIR: /usr/src/wordpress
      WP_TEST_DB_HOST: db:3306
      WP_TEST_DB_NAME: ${DB_NAME}
      WP_TEST_DB_USER: ${DB_USER}
      WP_TEST_DB_PASSWORD: ${DB_PASSWORD}
      WP_PHP_BINARY: php
    volumes:
      - ./:/workspace
      - ./wp-content:/var/www/html/wp-content
    command: ["sh", "-lc", "php ./vendor/bin/phpunit"]
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio_phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8081:80"   # maps phpMyAdmin to http://localhost:8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  db_data:
