name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 50.6.245.120
          username: letmckmy
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/repositories/wp-portfolio
            git fetch origin
            git reset --hard origin/main
            GIT_WORK_TREE=/home2/letmckmy/public_html git checkout -f main